### ISSUE TITLE
ESP23 Modell

### ISSUE THREAD

**Issue by BennyBread** [timo1235/ocs2.x-esp32-software#1]
Hallo Timo. 

Kannst Du mir sagen welchen ESP32 Du verwendest, denn der den ich z.B: zu Hause habe hat mehr pins und ist also nicht kompatibel.
Ist von AzDelivery: [ESP32NodeMCU](https://www.az-delivery.de/products/esp32-developmentboard)

Deiner hat laut dem Board nur 30 Pins, meiner 38...

PS: Das Board macht einen sehr guten Eindruck. Ist diese Woche angekommen. Bin gerade dabei es zu bestücken.

**Comment by timo1235** [comment]
Hallo, du brauchst einen ESP32 Devkit DoIT V1. 
Ich plane bei der Boardversion den ESP32 auf dem Board zu integrieren, dann muss man den nicht extra kaufen.
