### ISSUE TITLE
Drive from Endstop Distanz

### ISSUE THREAD

**Issue by HaWiWe** [timo1235/ocs2.x-esp32-software#7]
Das ist eine Idee, kein Bug!

Ich fände es gut, wenn man die Distanz für jeden Stepper festlegen könnte, den er vom Endstop runterfährt. Ich habe z.B. auf meiner Z Achse vom Lowrider 3 eine Differenz auf den 1.2m von 0.22mm. So genau kann ich das nicht physisch einstellen, dass ich den Entstop genau die Distanz verschiebe. Es wäre demnach schön, wenn man in der Software festlegen könnte, wie weit jeder Motor wegfahren soll, nachdem der Endstop nicht mehr anschlägt, um eine möglichst 100% „Squareness“ zu erreichen.

**Comment by timo1235** [comment]
Ist eingebaut(aber noch nicht released)
 
Du kannst den aktuellen Stand der Software einmal herunterladen und testen, ob´s bei dir klappt.

**Comment by HaWiWe** [comment]
Super, vielen Dank. Gerade habe ich relativ viel um die Ohren, wenn ich Luft habe, werde ich es testen.

**Comment by HaWiWe** [comment]
Also build lief schon mal durch ohne Fehler. Ist aber ja auch doch schon im Main Release und es hat sich noch niemand beschwert. :)
